# a mybinder.org-ready environment for demoing jupyterlab-dagitty
# this environment may also be used locally on Linux/MacOS/Windows, e.g.
#
#   conda env update --file binder/environment.yml
#   conda activate jupyterlab-dagitty-demo
#
name: jupyterlab-dagitty-demo

channels:
  - conda-forge

dependencies:
  # runtime dependencies
  - python >=3.10
  - jupyterlab >=4.0.0,<5
  # labextension build dependencies: postBuild builds from source
  - nodejs >=22.12   # @rspack/core requires ^20.19.0 || >=22.12.0
  - wget   # for build_dagitty.sh
  - pip
  - wheel
  - r-irkernel
  - r-dagitty   # for demonstration only
