# a mybinder.org-ready environment for demoing jupyterlab-dagitty
# this environment may also be used locally on Linux/MacOS/Windows, e.g.
#
#   conda env update --file binder/environment.yml
#   conda activate jupyterlab-dagitty-demo
#
name: jupyterlab-dagitty-demo

channels:
  - conda-forge

dependencies:
  # runtime dependencies
  - python >=3.10
  - jupyterlab >=4.0.0,<5
  - pip
  - wheel
  - r-irkernel
  - r-dagitty   # for demonstration only
  - pip:
    - jupyterlab-dagitty>=0.4.0
